language: python
python:
  - "3.9"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

before_install:
  - pip install -U pip wheel
  - pip install poetry

install:
  - poetry install

script:
  - poetry run pre-commit install --install-hooks
  - poetry run pre-commit run --all
  - poetry build
